import React from "react";

export const reportData = [
  {
    date: "07/12/24",
    vitals: {
      bloodTemp: "36.5",
      pulseRate: "63",
      respRate: "14",
      bloodPressure: "120/80",
      bloodOxygen: "98%",
      bodyWeight: "63kg",
      bloodGlucose: "85mg/DL",
    },
    exerciseLog: {
      walking: "10km",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "08/12/24",
    vitals: {
      bloodTemp: "36.5",
      pulseRate: "83",
      respRate: "12",
      bloodPressure: "118/78",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "92mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "09/12/24",
    vitals: {
      bloodTemp: "37.2",
      pulseRate: "73",
      respRate: "18",
      bloodPressure: "122/82",
      bloodOxygen: "99%",
      bodyWeight: "64kg",
      bloodGlucose: "89mg/DL",
    },
    exerciseLog: {
      walking: "10km",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "10/12/24",
    vitals: {
      bloodTemp: "36.8",
      pulseRate: "85",
      respRate: "15",
      bloodPressure: "115/75",
      bloodOxygen: "96%",
      bodyWeight: "63kg",
      bloodGlucose: "90mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "5km",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "11/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "78",
      respRate: "19",
      bloodPressure: "124/80",
      bloodOxygen: "98%",
      bodyWeight: "63kg",
      bloodGlucose: "95mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "12/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "84",
      respRate: "13",
      bloodPressure: "117/76",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "87mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7.5km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "13/12/24",
    vitals: {
      bloodTemp: "36.5",
      pulseRate: "83",
      respRate: "12",
      bloodPressure: "118/78",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "92mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "14/12/24",
    vitals: {
      bloodTemp: "37.2",
      pulseRate: "73",
      respRate: "18",
      bloodPressure: "122/82",
      bloodOxygen: "99%",
      bodyWeight: "64kg",
      bloodGlucose: "89mg/DL",
    },
    exerciseLog: {
      walking: "10km",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "15/12/24",
    vitals: {
      bloodTemp: "36.8",
      pulseRate: "85",
      respRate: "15",
      bloodPressure: "115/75",
      bloodOxygen: "96%",
      bodyWeight: "63kg",
      bloodGlucose: "90mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "5km",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "16/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "78",
      respRate: "19",
      bloodPressure: "124/80",
      bloodOxygen: "98%",
      bodyWeight: "63kg",
      bloodGlucose: "95mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "17/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "84",
      respRate: "13",
      bloodPressure: "117/76",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "87mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7.5km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "18/12/24",
    vitals: {
      bloodTemp: "36.5",
      pulseRate: "83",
      respRate: "12",
      bloodPressure: "118/78",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "92mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "19/12/24",
    vitals: {
      bloodTemp: "37.2",
      pulseRate: "73",
      respRate: "18",
      bloodPressure: "122/82",
      bloodOxygen: "99%",
      bodyWeight: "64kg",
      bloodGlucose: "89mg/DL",
    },
    exerciseLog: {
      walking: "10km",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "20/12/24",
    vitals: {
      bloodTemp: "36.8",
      pulseRate: "85",
      respRate: "15",
      bloodPressure: "115/75",
      bloodOxygen: "96%",
      bodyWeight: "63kg",
      bloodGlucose: "90mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "5km",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "21/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "78",
      respRate: "19",
      bloodPressure: "124/80",
      bloodOxygen: "98%",
      bodyWeight: "63kg",
      bloodGlucose: "95mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "22/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "84",
      respRate: "13",
      bloodPressure: "117/76",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "87mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7.5km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "23/12/24",
    vitals: {
      bloodTemp: "36.5",
      pulseRate: "83",
      respRate: "12",
      bloodPressure: "118/78",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "92mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "24/12/24",
    vitals: {
      bloodTemp: "37.2",
      pulseRate: "73",
      respRate: "18",
      bloodPressure: "122/82",
      bloodOxygen: "99%",
      bodyWeight: "64kg",
      bloodGlucose: "89mg/DL",
    },
    exerciseLog: {
      walking: "10km",
      jogging: "",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "25/12/24",
    vitals: {
      bloodTemp: "36.8",
      pulseRate: "85",
      respRate: "15",
      bloodPressure: "115/75",
      bloodOxygen: "96%",
      bodyWeight: "63kg",
      bloodGlucose: "90mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "",
      running: "5km",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "26/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "78",
      respRate: "19",
      bloodPressure: "124/80",
      bloodOxygen: "98%",
      bodyWeight: "63kg",
      bloodGlucose: "95mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
  {
    date: "27/12/24",
    vitals: {
      bloodTemp: "36.7",
      pulseRate: "84",
      respRate: "13",
      bloodPressure: "117/76",
      bloodOxygen: "97%",
      bodyWeight: "63kg",
      bloodGlucose: "87mg/DL",
    },
    exerciseLog: {
      walking: "",
      jogging: "7.5km",
      running: "",
      cycling: "",
      skipping: "",
      yoga: "1hr",
      dance: "",
    },
  },
];
